export const CHANGE_QUOTATION_TO = "CHANGE_QUOTATION_TO";
export const CHANGE_QUOTATION_BODY = "CHANGE_QUOTATION_BODY";
export const CHANGE_QUOTATION_DESCRIPTION = "CHANGE_QUOTATION_DESCRIPTION";
export const CHANGE_QUOTATION_AMOUNT = "CHANGE_QUOTATION_AMOUNT";
export const CHANGE_QUOTATION_DATE = "CHANGE_QUOTATION_DATE";
export const ADD_NEW_FIELD = "ADD_NEW_FIELD";

export const FETCH_QUOTATIONS_REQUEST = "FETCH_QUOTATIONS_REQUEST";
export const FETCH_QUOTATIONS_SUCCESS = "FETCH_QUOTATIONS_SUCCESS";
export const FETCH_QUOTATIONS_FAIL = "FETCH_QUOTATIONS_FAIL";

export const POST_QUOTATION_REQUEST = "POST_QUOTATION_REQUEST";
export const POST_QUOTATION_SUCCESS = "POST_QUOTATION_SUCCESS";
export const POST_QUOTATION_FAIL = "POST_QUOTATION_FAIL";